backend_admin:
    resource: "@BackendAdminBundle/Resources/config/routing.yml"
    prefix:   /panel

backend_user:
    resource: "@BackendUserBundle/Resources/config/routing.yml"
    prefix:   /panel/user

backend_customer:
    resource: "@BackendCustomerBundle/Resources/config/routing.yml"
    prefix:   /panel/customer

customer_administrador:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing.yml"
    prefix:   /customer        

frontend:
    resource: "@FrontendHomeBundle/Resources/config/routing.yml"
    prefix:   /

backend_group:
    resource: "@BackendUserBundle/Resources/config/group.yml"
    prefix:   /panel/group
    
backend_seteo:
    resource: "@BackendUserBundle/Resources/config/seteo.yml"
    prefix:   /panel/seteo

login:
    pattern: /panel/login
    defaults: { _controller: BackendUserBundle:Default:login }

login_check:
    pattern: /panel/login_check

logout:
    path: /panel/logout
    
register_user:
    pattern:  /register_user
    defaults: { _controller: "BackendUserBundle:User:register" }

activate_account:
    pattern:  /activar/{codigo}
    defaults: { _controller: "BackendUserBundle:User:activateAccount", codigo: '' }


forgot_pass:
    pattern:  /forgot_pass
    defaults: { _controller: "BackendUserBundle:User:forgotPassword" }

change_pass:
    pattern:  /change_pass/{codigo}
    defaults: { _controller: "BackendUserBundle:User:changePassword", codigo: '' }    
    
access_denied:
    pattern: /panel/caes
    defaults: { _controller: BackendAdminBundle:Default:access }    

principal:
   pattern: /panel/principal
   defaults: { _controller: BackendAdminBundle:Default:index  }        

customer_access_denied:
    pattern: /access_denied
    defaults: { _controller: BackendCustomerAdminBundle:Principal:access }