customer_principal:
    pattern:  /
    defaults: { _controller: BackendCustomerAdminBundle:Principal:index }

customer_blank:
    pattern:  /blank
    defaults: { _controller: BackendCustomerAdminBundle:Principal:blank }

customer_profile:
    path: /customer_profile
    defaults: { _controller:BackendCustomerAdminBundle:Principal:profile }


frontend_login:        
    pattern:  /loginFront
    defaults: { _controller: "BackendCustomerAdminBundle:Principal:loginFront" }
    

customer_login:
    pattern: /login
    defaults: { _controller: BackendCustomerBundle:Default:login }

customer_auth:
    pattern: /login_check

customer_logout:
    path: /logout 

customer_direccion:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/direccion.yml"
    prefix:   /direccion

customer_favorito:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/favorito.yml"
    prefix:   /favorito        

customer_sucursal:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/sucursal.yml"
    prefix:   /sucursal    

customer_producto:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/producto.yml"
    prefix:   /producto

customer_variedad:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/variedad.yml"
    prefix:   /variedad  

customer_pedido:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/pedido.yml"
    prefix:   /pedido  

customer_compra:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/compra.yml"
    prefix:   /compra
            
customer_promocion:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/promocion.yml"
    prefix:   /promocion

customer_banner:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/banner.yml"
    prefix:   /banner

customer_region:
    resource: "@BackendCustomerAdminBundle/Resources/config/routing/region.yml"
    prefix:   /region